"""Stream the response cache into an OME-952 snapshot archive (OME-1021).

The weekly archive's trust boundary: everything downstream — the existing loader
(``bulk_loader.load_snapshot``), ``restore-cache``, any future restore path — consumes the
bytes this module emits, byte for byte. The contract is the OME-952 one
(:mod:`.snapshot`): a gzip'd data-only dump of ``request_cache_entries`` whose COPY block
names ``CANONICAL_COLUMNS`` verbatim, carries the rows a live ``COPY … TO STDOUT``
produced, and ends at a ``\\.`` terminator; plus a ``SnapshotManifest`` sidecar whose
``row_count`` / ``sha256`` / ``revisions`` are the true ones.

WHY a dedicated asyncpg connection and not the shared Tortoise pool: a weekly COPY holds
whatever connection it runs on for the whole export, and the request path must never wait
on a backup. The pool stays untouched; the exporter opens its own connection from the same
DSN and closes it in ``finally``.

WHY ``asyncio.to_thread`` around every gzip write: gzip compression is CPU and the file
write is blocking I/O — both off the event loop the gateway serves on, exactly the
discipline ``bulk_loader._read_batch`` already applies to gzip reads.

INVARIANT: the sha256 the manifest declares is the hash of the gzip FILE, not of the
uncompressed rows — the loader verifies it against the uploaded bytes
(``digest_matches``), so it must be computed over the compressed stream (the hashing tee
wraps the raw file, beneath the gzip wrapper).
"""

from __future__ import annotations

import asyncio
import gzip
import hashlib
import logging
import re
import shutil
import tempfile
from collections.abc import Awaitable, Callable, Mapping
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import BinaryIO, Protocol

import asyncpg

from .revisions import active_cache_revisions
from .snapshot import CANONICAL_COLUMNS, SnapshotManifest

logger = logging.getLogger(__name__)

_TABLE = "request_cache_entries"
_SNAPSHOT_SCHEMA = "screamingface.cache-snapshot.v1"
_COPY_SELECT = f"SELECT {', '.join(CANONICAL_COLUMNS)} FROM {_TABLE}"
_HEADER_LINE = f"COPY public.{_TABLE} ({', '.join(CANONICAL_COLUMNS)}) FROM stdin;\n"
_STATUS_PATTERN = re.compile(r"^COPY (\d+)$")
_CONNECT_TIMEOUT_S = 10
_COPY_TIMEOUT_S = 600.0

DEFAULT_MAX_SNAPSHOT_BYTES = 512 * 1024 * 1024
"""Spool cap for one archive. The gateway's temp dir is shared with the database host, so
a runaway table must fail the run loudly rather than fill the pod disk."""

# Data-only preamble and epilogue mirror make_pg_snapshot: the loader scans for the COPY
# header and never reads past `\.`, so these are cosmetic — but they keep the artifact a
# dump a human can read and psql can replay.
_PREAMBLE = """\
--
-- ScreamingFace response-cache snapshot (data only)
-- Generated by the aigateway snapshot exporter from request_cache_entries.
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

"""

_EPILOGUE = """
--
-- ScreamingFace response-cache snapshot complete
--
"""


class SnapshotExportError(RuntimeError):
    """The export failed; the spool has been cleaned and nothing was published."""


class SnapshotExportUnsupportedDatabase(SnapshotExportError):
    """The configured DSN is not Postgres, so COPY cannot run."""


class SnapshotExportDatabaseUnavailable(SnapshotExportError):
    """The dedicated connection could not be established."""


class SnapshotExportCopyFailed(SnapshotExportError):
    """The COPY command failed or returned an unreadable status."""


class SnapshotExportSpoolExceeded(SnapshotExportError):
    """The archive exceeded the configured spool cap."""


type Connect = Callable[[], Awaitable["_CopyConnection"]]
type RevisionSource = Callable[[], Mapping[str, str]]
type Clock = Callable[[], datetime]


class _CopyConnection(Protocol):
    """The asyncpg surface the exporter drives: one streaming COPY, one close."""

    async def copy_from_query(
        self,
        query: str,
        *,
        output: Callable[[bytes], Awaitable[None]],
        timeout: float | None = None,
    ) -> str: ...

    async def close(self) -> None: ...


class _HashingSink:
    """A binary file wrapper that hashes every byte written — the gzip'd bytes."""

    def __init__(self, raw: BinaryIO) -> None:
        self._raw = raw
        self._digest = hashlib.sha256()
        self.total = 0

    def write(self, data: bytes) -> int:
        self._digest.update(data)
        self.total += len(data)
        return self._raw.write(data)

    def flush(self) -> None:
        # gzip.flush() propagates to the fileobj; the raw file's buffer must follow.
        self._raw.flush()

    @property
    def hexdigest(self) -> str:
        return self._digest.hexdigest()


@dataclass(frozen=True, slots=True)
class SnapshotExport:
    """One produced snapshot pair, named for its unique object-storage stamp."""

    archive_path: Path
    manifest_path: Path
    row_count: int
    sha256_hex: str
    started_at: datetime
    stamp: str
    """UTC run stamp, path-safe: ``2026-08-28T05-00-00Z``. Object keys are
    ``cache-snapshots/<stamp>.sql.gz`` / ``…manifest.json`` (spec §4.1)."""


async def postgres_connect(dsn: str) -> _CopyConnection:
    """Open a dedicated asyncpg connection for one export (never the shared pool).

    Raises:
        SnapshotExportUnsupportedDatabase: the DSN is not a Postgres URL.
        SnapshotExportDatabaseUnavailable: the connection could not be established.
    """
    scheme = dsn.split("://", 1)[0].lower() if "://" in dsn else ""
    if scheme not in {"postgres", "postgresql"}:
        raise SnapshotExportUnsupportedDatabase(
            "the cache snapshot export speaks Postgres COPY; this DSN is not a "
            f"Postgres URL (scheme {scheme!r})"
        )
    try:
        return await asyncpg.connect(dsn=dsn, timeout=_CONNECT_TIMEOUT_S)
    except (TimeoutError, OSError, asyncpg.PostgresError) as exc:
        raise SnapshotExportDatabaseUnavailable(
            f"could not connect to the database for the cache snapshot export: {exc}"
        ) from exc


class CacheSnapshotExporter:
    """Produce one OME-952 snapshot pair from the live cache table.

    Everything is injectable for tests: the connection factory, the revision source, the
    clock, the spool directory and the size cap. Production wiring (the scheduler,
    ``_lifespan``) supplies ``postgres_connect(database_url)`` and
    ``active_cache_revisions``.
    """

    def __init__(
        self,
        connect: Connect,
        *,
        revisions: RevisionSource = active_cache_revisions,
        now: Clock | None = None,
        spool_dir: str | None = None,
        max_bytes: int = DEFAULT_MAX_SNAPSHOT_BYTES,
    ) -> None:
        self._connect = connect
        self._revisions = revisions
        self._now = now if now is not None else lambda: datetime.now(UTC)
        self._spool_dir = spool_dir
        self._max_bytes = max_bytes

    async def export(self) -> SnapshotExport:
        """Produce the archive + manifest in a fresh spool directory and return them.

        On success the spool is left in place for the caller to publish and then remove
        (``shutil.rmtree(export.archive_path.parent)``). On any failure the whole spool
        directory is removed before the error propagates.
        """
        started_at = self._now()
        stamp = started_at.astimezone(UTC).strftime("%Y-%m-%dT%H-%M-%SZ")
        spool = Path(tempfile.mkdtemp(prefix="cache-snapshot-", dir=self._spool_dir))
        archive_path = spool / f"{stamp}.sql.gz"
        manifest_path = spool / f"{stamp}.manifest.json"
        try:
            connection = await self._connect()
            try:
                row_count, sha256_hex = await self._archive(connection, archive_path)
            finally:
                await connection.close()
            manifest = SnapshotManifest(
                schema=_SNAPSHOT_SCHEMA,
                generated_at=started_at.astimezone(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
                row_count=row_count,
                sha256=sha256_hex,
                revisions=dict(self._revisions()),
            )
            await asyncio.to_thread(
                manifest_path.write_text, manifest.model_dump_json(), encoding="utf-8"
            )
            return SnapshotExport(
                archive_path=archive_path,
                manifest_path=manifest_path,
                row_count=row_count,
                sha256_hex=sha256_hex,
                started_at=started_at,
                stamp=stamp,
            )
        except BaseException:
            shutil.rmtree(spool, ignore_errors=True)
            raise

    async def _archive(self, connection: _CopyConnection, destination: Path) -> tuple[int, str]:
        """Stream the table into ``destination`` as a gzip'd COPY dump.

        Returns (row_count, sha256 of the gzip file).
        """
        raw = destination.open("wb")
        sink = _HashingSink(raw)
        gz = gzip.GzipFile(fileobj=sink, mode="wb")

        async def _write(chunk: bytes) -> None:
            await asyncio.to_thread(gz.write, chunk)
            # gzip buffers internally — flush so the sink sees the bytes actually written
            # to disk, which is what the cap guards (and the digest covers).
            await asyncio.to_thread(gz.flush)
            if sink.total > self._max_bytes:
                raise SnapshotExportSpoolExceeded(
                    f"the cache snapshot archive exceeded the {self._max_bytes} byte cap "
                    f"(at least {sink.total} bytes)"
                )

        try:
            try:
                await _write(_PREAMBLE.encode("utf-8"))
                await _write(_HEADER_LINE.encode("utf-8"))
                try:
                    status = await connection.copy_from_query(
                        _COPY_SELECT, output=_write, timeout=_COPY_TIMEOUT_S
                    )
                except SnapshotExportError:
                    raise
                except Exception as exc:
                    raise SnapshotExportCopyFailed(
                        f"the cache COPY failed: {type(exc).__name__}: {exc}"
                    ) from exc
                await _write(b"\\.\n")
                await _write(_EPILOGUE.encode("utf-8"))
            finally:
                # gzip does not close its fileobj — flush the trailer first, then the raw
                # file, so the digest covers every compressed byte that hit the disk.
                await asyncio.to_thread(gz.close)
        finally:
            raw.close()
        return _row_count(status), sink.hexdigest


def _row_count(status: str) -> int:
    match = _STATUS_PATTERN.fullmatch(status.strip())
    if match is None:
        raise SnapshotExportCopyFailed(
            f"the database returned an unreadable COPY status: {status!r}"
        )
    return int(match.group(1))


__all__ = [
    "CacheSnapshotExporter",
    "Connect",
    "DEFAULT_MAX_SNAPSHOT_BYTES",
    "SnapshotExport",
    "SnapshotExportCopyFailed",
    "SnapshotExportDatabaseUnavailable",
    "SnapshotExportError",
    "SnapshotExportSpoolExceeded",
    "SnapshotExportUnsupportedDatabase",
    "postgres_connect",
]
