"""The imported boards' LOCKFILE — treat this module exactly like ``uv.lock``.

Like a lockfile, this is frozen, reviewable DATA, not logic: one small set of rows
per imported board, and the diff to these rows IS the exam changing. Every value
participates in the board's revision hash (spec §6: revision = sha over the pinned
package identity + the imported case subset's identity), so changing one changes
every route address — an expression addressed to an old revision never resolves
against a changed exam.

Also like a lockfile, the rows are of three kinds, written by different authors:

1. COPIED from the eval's source (dataset path / config / split): the values the
   eval's own task passes to ``hf_dataset(...)``. They live inside function bodies
   upstream, not exported constants, so they are transcribed here with the source
   named — verified against inspect-evals 0.20.0 on 2026-09-15.
2. CAPTURED at import time (dataset revision sha, case count): most inspect_evals
   tasks do NOT pin a HF revision — they fetch the Hub's latest. These rows record
   what HEAD resolved to when we froze the exam, the way a lockfile records the
   resolved version, and the count is the bake's drift guard (prepare refuses a
   dataset that no longer yields exactly this many rows). They cannot be derived
   from any code; they are observations.
3. OURS by policy (shuffle seed, preparer/protocol revisions): decisions this repo
   makes about how the exam is administered, not facts about upstream.

WHY frozen data instead of resolving at build or run time: a reviewable diff is the
security property. Builds fetch by the recorded sha and runs never fetch at all
(assets are baked into the image, OME-925), so a drifted or compromised upstream
can change nothing without a visible edit to this file. Import time — the moment a
row is first written — is the ONLY trust window, which is why new rows arrive as a
generated, human-reviewed diff (pin generator: follow-up on OME-1116).
"""

from __future__ import annotations

from importlib.metadata import version

# gsm8k — their gsm8k.py pins (hf_dataset path/data_dir/split/revision).
# https://huggingface.co/datasets/openai/gsm8k/tree/cc7b047b6e5bb11b4f1af84efc572db110a51b3c
GSM8K_DATASET = "openai/gsm8k"
GSM8K_DATA_DIR = "main"
GSM8K_SPLIT = "test"
GSM8K_DATASET_REVISION = "cc7b047b6e5bb11b4f1af84efc572db110a51b3c"
GSM8K_CASE_COUNT = 1319

# mmlu — their mmlu.py pins (mmlu_0_shot's EN_US path).
# https://huggingface.co/datasets/cais/mmlu/tree/c30699e8356da336a370243923dbaf21066bb9fe
MMLU_DATASET = "cais/mmlu"
MMLU_CONFIG = "all"
MMLU_SPLIT = "test"
MMLU_DATASET_REVISION = "c30699e8356da336a370243923dbaf21066bb9fe"
MMLU_CASE_COUNT = 14042
# WHY a seeded shuffle: the HF split is subject-grouped, so an unshuffled `limit=N`
# run would examine one subject only. The seed is exam identity (it fixes which
# cases a limit selects), so it rides the revision hash.
MMLU_SHUFFLE_SEED = 20260915

# arc_easy — generated by the importer on 2026-09-17 from
#   inspect_evals.arc.arc:arc_easy;
# license: cc-by-sa-4.0. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/allenai/ai2_arc/tree/210d026faf9955653af8916fad021475a3f00453
ARC_EASY_DATASET = "allenai/ai2_arc"
ARC_EASY_CONFIG = "ARC-Easy"
ARC_EASY_SPLIT = "test"
ARC_EASY_DATASET_REVISION = "210d026faf9955653af8916fad021475a3f00453"
ARC_EASY_CASE_COUNT = 2376

# arc_challenge — generated by the importer on 2026-09-17 from
#   inspect_evals.arc.arc:arc_challenge;
# license: cc-by-sa-4.0. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/allenai/ai2_arc/tree/210d026faf9955653af8916fad021475a3f00453
ARC_CHALLENGE_DATASET = "allenai/ai2_arc"
ARC_CHALLENGE_CONFIG = "ARC-Challenge"
ARC_CHALLENGE_SPLIT = "test"
ARC_CHALLENGE_DATASET_REVISION = "210d026faf9955653af8916fad021475a3f00453"
ARC_CHALLENGE_CASE_COUNT = 1172

# commonsense_qa — generated by the importer on 2026-09-17 from
#   inspect_evals.commonsense_qa.commonsense_qa:commonsense_qa;
# license: mit. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/tau/commonsense_qa/tree/94630fe30dad47192a8546eb75f094926d47e155
COMMONSENSE_QA_DATASET = "tau/commonsense_qa"
COMMONSENSE_QA_CONFIG = ""
COMMONSENSE_QA_SPLIT = "validation"
COMMONSENSE_QA_DATASET_REVISION = "94630fe30dad47192a8546eb75f094926d47e155"
COMMONSENSE_QA_CASE_COUNT = 1221
# WHY the seed: the upstream eval shuffles its exam order on every run
# (hf_dataset shuffle=True, no seed), so the import pins ONE order as exam
# identity; the seed rides the revision hash (review round 2026-09-17).
COMMONSENSE_QA_SHUFFLE_SEED = 20260917

# paws — generated by the importer on 2026-09-17 from
#   inspect_evals.paws.paws:paws;
# license: other. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/google-research-datasets/paws/tree/161ece9501cf0a11f3e48bd356eaa82de46d6a09
PAWS_DATASET = "google-research-datasets/paws"
PAWS_CONFIG = "labeled_final"
PAWS_SPLIT = "test"
PAWS_DATASET_REVISION = "161ece9501cf0a11f3e48bd356eaa82de46d6a09"
PAWS_CASE_COUNT = 8000
# WHY the seed: the upstream eval shuffles its exam order on every run
# (hf_dataset shuffle=True, no seed), so the import pins ONE order as exam
# identity; the seed rides the revision hash (review round 2026-09-17).
PAWS_SHUFFLE_SEED = 20260917

# boolq — generated by the importer on 2026-09-17 from
#   inspect_evals.boolq.boolq:boolq;
# license: cc-by-sa-3.0. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/google/boolq/tree/35b264d03638db9f4ce671b711558bf7ff0f80d5
BOOLQ_DATASET = "google/boolq"
BOOLQ_CONFIG = ""
BOOLQ_SPLIT = "validation"
BOOLQ_DATASET_REVISION = "35b264d03638db9f4ce671b711558bf7ff0f80d5"
BOOLQ_CASE_COUNT = 3270
# WHY the seed: the upstream eval shuffles its exam order on every run
# (hf_dataset shuffle=True, no seed), so the import pins ONE order as exam
# identity; the seed rides the revision hash (review round 2026-09-17).
BOOLQ_SHUFFLE_SEED = 20260917

# mmlu_pro — generated by the importer on 2026-09-17 from
#   inspect_evals.mmlu_pro.mmlu_pro:mmlu_pro;
# license: mit. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/TIGER-Lab/MMLU-Pro/tree/527feea0afed1de15a8c115abf7be4c912123315
MMLU_PRO_DATASET = "TIGER-Lab/MMLU-Pro"
MMLU_PRO_CONFIG = ""
MMLU_PRO_SPLIT = "test"
MMLU_PRO_DATASET_REVISION = "527feea0afed1de15a8c115abf7be4c912123315"
MMLU_PRO_CASE_COUNT = 12032
# WHY the seed: the upstream eval shuffles per run (shuffle=True, no seed) AND
# the split is category-grouped — the seed pins one order as exam identity so
# a limit=N run spans disciplines (review round 2026-09-17).
MMLU_PRO_SHUFFLE_SEED = 20260917

# winogrande — generated by the importer on 2026-09-17 from
#   inspect_evals.winogrande.winogrande:winogrande, imported at fewshot=0
#   (upstream default 5 would prepend a fewshot system message the bake drops);
# license: UNKNOWN. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/allenai/winogrande/tree/01e74176c63542e6b0bcb004dcdea22d94fb67b5
WINOGRANDE_DATASET = "allenai/winogrande"
WINOGRANDE_CONFIG = "winogrande_xl"
WINOGRANDE_SPLIT = "validation"
WINOGRANDE_DATASET_REVISION = "01e74176c63542e6b0bcb004dcdea22d94fb67b5"
# Upstream wraps the load in filter_duplicate_ids(); verified content-preserving
# at this revision (0 duplicate ids — row count unchanged), 2026-09-17.
WINOGRANDE_CASE_COUNT = 1267

# race_h — generated by the importer on 2026-09-17 from
#   inspect_evals.race_h.race_h:race_h;
# license: other. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/ehovy/race/tree/2fec9fd81f1dc971569a9b729c43f2f0e6436637
RACE_H_DATASET = "ehovy/race"
RACE_H_CONFIG = "high"
RACE_H_SPLIT = "test"
RACE_H_DATASET_REVISION = "2fec9fd81f1dc971569a9b729c43f2f0e6436637"
# Upstream wraps the load in filter_duplicate_ids(); verified content-preserving
# at this revision (0 duplicate ids — row count unchanged), 2026-09-17.
RACE_H_CASE_COUNT = 3498
# WHY the seed: the upstream eval shuffles per run (shuffle=True, no seed) AND
# questions arrive in per-passage runs — the seed pins one order as exam
# identity so a limit=N run spans passages (review round 2026-09-17).
RACE_H_SHUFFLE_SEED = 20260917

# aime24 — generated by the importer on 2026-09-22 from
#   inspect_evals.aime2024.aime2024:aime2024;
# license: mit. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/Maxwell-Jia/AIME_2024/tree/8d88b2876a82a080e2f172cc9b25d0d9d2cb4792
AIME24_DATASET = "Maxwell-Jia/AIME_2024"
AIME24_CONFIG = ""
AIME24_SPLIT = "train"
AIME24_DATASET_REVISION = "8d88b2876a82a080e2f172cc9b25d0d9d2cb4792"
AIME24_CASE_COUNT = 30
AIME24_SHUFFLE_SEED = 20260922

# aime25 — generated by the importer on 2026-09-22 from
#   inspect_evals.aime2025.aime2025:aime2025;
# license: apache-2.0. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/math-ai/aime25/tree/563bb8404243c5f09de6ec262f2db674fe5bce9b
AIME25_DATASET = "math-ai/aime25"
AIME25_CONFIG = ""
AIME25_SPLIT = "test"
AIME25_DATASET_REVISION = "563bb8404243c5f09de6ec262f2db674fe5bce9b"
AIME25_CASE_COUNT = 30
AIME25_SHUFFLE_SEED = 20260922

# musr — generated by the importer on 2026-09-22 from
#   inspect_evals.musr.musr:musr;
# license: cc-by-4.0. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/TAUR-Lab/MuSR/tree/7c365b439a222150f317764d4f16ae6c96d7d94a
MUSR_DATASET = "TAUR-Lab/MuSR"
MUSR_CONFIG = ""
MUSR_SPLIT = "murder_mysteries"
MUSR_DATASET_REVISION = "7c365b439a222150f317764d4f16ae6c96d7d94a"
MUSR_CASE_COUNT = 250
MUSR_SHUFFLE_SEED = 20260922

# wmdp_bio — generated by the importer on 2026-09-22 from
#   inspect_evals.wmdp.wmdp:wmdp_bio;
# license: mit. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/cais/wmdp/tree/7125571f22f032c56415e7980f48d877dd830ff8
WMDP_BIO_DATASET = "cais/wmdp"
WMDP_BIO_CONFIG = "wmdp-bio"
WMDP_BIO_SPLIT = "test"
WMDP_BIO_DATASET_REVISION = "7125571f22f032c56415e7980f48d877dd830ff8"
WMDP_BIO_CASE_COUNT = 1273

# wmdp_chem — generated by the importer on 2026-09-22 from
#   inspect_evals.wmdp.wmdp:wmdp_chem;
# license: mit. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/cais/wmdp/tree/7125571f22f032c56415e7980f48d877dd830ff8
WMDP_CHEM_DATASET = "cais/wmdp"
WMDP_CHEM_CONFIG = "wmdp-chem"
WMDP_CHEM_SPLIT = "test"
WMDP_CHEM_DATASET_REVISION = "7125571f22f032c56415e7980f48d877dd830ff8"
WMDP_CHEM_CASE_COUNT = 408

# wmdp_cyber — generated by the importer on 2026-09-22 from
#   inspect_evals.wmdp.wmdp:wmdp_cyber;
# license: mit. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/cais/wmdp/tree/7125571f22f032c56415e7980f48d877dd830ff8
WMDP_CYBER_DATASET = "cais/wmdp"
WMDP_CYBER_CONFIG = "wmdp-cyber"
WMDP_CYBER_SPLIT = "test"
WMDP_CYBER_DATASET_REVISION = "7125571f22f032c56415e7980f48d877dd830ff8"
WMDP_CYBER_CASE_COUNT = 1987

# hellaswag — generated by the importer on 2026-09-22 from
#   inspect_evals.hellaswag.hellaswag:hellaswag;
# license: UNKNOWN. Review before merge — import time is the trust window.
# Owner-approved 2026-09-22: the HF card carries no licence tag, but the
# upstream source repo (github.com/rowanz/hellaswag) is MIT — MIT-per-source
# is the licence of record for this import.
# The revision sha is COPIED from upstream's own HELLASWAG_DATASET_REVISION
# constant (not merely captured) — the drift test pins the two together.
# https://huggingface.co/datasets/Rowan/hellaswag/tree/218ec52e09a7e7462a5400043bb9a69a41d06b76
HELLASWAG_DATASET = "Rowan/hellaswag"
HELLASWAG_CONFIG = ""
HELLASWAG_SPLIT = "validation"
HELLASWAG_DATASET_REVISION = "218ec52e09a7e7462a5400043bb9a69a41d06b76"
HELLASWAG_CASE_COUNT = 10042
# WHY the seed (OURS by policy — review finding on PR #1018): the pinned
# validation split is domain-grouped, 3,243 ActivityNet rows then 6,799
# WikiHow, so an unshuffled `limit=N` run with N ≤ 3243 would examine zero
# WikiHow cases. The seed pins one mixed order as exam identity.
HELLASWAG_SHUFFLE_SEED = 20260922

# frontierscience — generated by the importer on 2026-09-23 from
#   inspect_evals.frontierscience.frontierscience:frontierscience;
# license: apache-2.0. Review before merge — import time is the trust window.
# https://huggingface.co/datasets/openai/frontierscience/tree/25ed67db7da8f4591484e764008ff585544f5a30
FRONTIERSCIENCE_DATASET = "openai/frontierscience"
FRONTIERSCIENCE_CONFIG = ""
FRONTIERSCIENCE_SPLIT = "test"
FRONTIERSCIENCE_DATASET_REVISION = "25ed67db7da8f4591484e764008ff585544f5a30"
FRONTIERSCIENCE_CASE_COUNT = 160
FRONTIERSCIENCE_SHUFFLE_SEED = 20260923

# --- importer: generated pin rows land above this line ---

# WHY: prepare's emission rules are part of the exam; bump when they change.
PREPARER_REVISION = "inspect-single-shot-v1"
# WHY: the exchange itself — one candidate invocation, aggregate-side scoring.
PROTOCOL_REVISION = "inspect-single-shot-v1"


def pinned_inspect_packages() -> tuple[str, str]:
    """The installed inspect distributions as ``name==version`` identity strings.

    Spec §6 hashes "the pinned inspect-evals package digest"; with exact ``==``
    pins in the engine's ``inspect`` extra, the version string IS that identity.
    """

    return (
        f"inspect-ai=={version('inspect-ai')}",
        f"inspect-evals=={version('inspect-evals')}",
    )


__all__ = [
    "GSM8K_CASE_COUNT",
    "GSM8K_DATA_DIR",
    "GSM8K_DATASET",
    "GSM8K_DATASET_REVISION",
    "GSM8K_SPLIT",
    "MMLU_CASE_COUNT",
    "MMLU_CONFIG",
    "MMLU_DATASET",
    "MMLU_DATASET_REVISION",
    "MMLU_SHUFFLE_SEED",
    "MMLU_SPLIT",
    "PREPARER_REVISION",
    "PROTOCOL_REVISION",
    "pinned_inspect_packages",
]
