/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate an account and return a stateless JWT session.
         *
         *     Inactive accounts receive the same generic 401 as bad credentials (no
         *     account-status disclosure, per OWASP); the refusal is logged server-side.
         */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Account */
        post: operations["create_account_v1_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_v1_admin_accounts_get"];
        put?: never;
        /**
         * Create Account
         * @description Provision a tenant ahead of their first request.
         *
         *     Delegates to `account_for_identity`, the SAME function `current_account` uses when a caller
         *     arrives unprovisioned. One code path means an admin-created account and an auto-created one are
         *     byte-identical, the address normalisation cannot drift between them, and the get-or-create race
         *     handling comes for free.
         *
         *     Consequently this is idempotent: creating an account that exists returns it rather than 409.
         *     That is the honest contract — the account WILL exist the moment its owner sends a request, so
         *     there is no state in which "already exists" is an error the operator can act on.
         */
        post: operations["create_account_v1_admin_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account_v1_admin_accounts__account_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Account
         * @description Rename or deactivate a tenant.
         *
         *     There is no DELETE. `oauth_connections.account_id` cascades on delete, and the account's
         *     `credential_blobs` have no foreign key at all — so a real delete would take the connections
         *     with it and leave the encrypted blobs orphaned. Deactivation is the reversible equivalent:
         *     `account_for_identity` returns None for an inactive account, so the next request 401s.
         */
        patch: operations["patch_account_v1_admin_accounts__account_id__patch"];
        trace?: never;
    };
    "/v1/admin/accounts/{account_id}/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Account Profiles
         * @description List one tenant's credential profiles.
         *
         *     No new store code was needed: `ProfileIndexStore.list` has always taken the account as an
         *     argument — the tenant-facing route simply always passes the caller's own id. Cross-account
         *     access is a different argument, not a different store.
         */
        get: operations["list_account_profiles_v1_admin_accounts__account_id__profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/accounts/{account_id}/profiles/{provider}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account Profile
         * @description Remove a tenant's profile and its stored credential.
         *
         *     Delegates to the same implementation as the tenant-facing delete, which publishes the index
         *     removal and the credential deletion in one transaction so a committed delete never leaves an
         *     orphaned blob.
         */
        delete: operations["delete_account_profile_v1_admin_accounts__account_id__profiles__provider___name__delete"];
        options?: never;
        head?: never;
        /** Patch Account Profile */
        patch: operations["patch_account_profile_v1_admin_accounts__account_id__profiles__provider___name__patch"];
        trace?: never;
    };
    "/v1/admin/accounts/{account_id}/profiles/{provider}/{name}/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Account Api Key
         * @description Attach or replace a tenant's provider API key. This is the point of the whole console.
         *
         *     Delegates to `upsert_api_key_profile`, the SAME implementation the tenant-facing route uses.
         *     That function carries the OME-307 transaction-ordering invariants (index CAS first, credential
         *     write second, rollback as the sole atomicity mechanism); a second copy written for this path
         *     would be a second place for them to rot.
         *
         *     The raw key is never echoed back — the response carries only the masked `account_label`.
         */
        put: operations["set_account_api_key_v1_admin_accounts__account_id__profiles__provider___name__api_key_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/cache/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cache Info */
        get: operations["cache_info_v1_admin_cache_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/cache/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Snapshot */
        post: operations["upload_snapshot_v1_admin_cache_snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/cache/snapshots/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cache Jobs */
        get: operations["list_cache_jobs_v1_admin_cache_snapshots_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/cache/snapshots/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cache Job */
        get: operations["get_cache_job_v1_admin_cache_snapshots_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth/connections/api-key/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Api Key
         * @description Validate authentication and readiness; the minimal inference may consume quota or credit.
         */
        post: operations["validate_api_key_v1_oauth_connections_api_key_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_v1_auth_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/{provider}/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Provider Profiles */
        get: operations["list_provider_profiles_v1_auth__provider__profiles_get"];
        put?: never;
        /** Start Oauth */
        post: operations["start_oauth_v1_auth__provider__profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/{provider}/profiles/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_v1_auth__provider__profiles__name__get"];
        put?: never;
        post?: never;
        /**
         * Delete Profile
         * @description Delete the CALLER's own profile. Thin wrapper over the shared implementation.
         */
        delete: operations["delete_profile_v1_auth__provider__profiles__name__delete"];
        options?: never;
        head?: never;
        /** Patch Profile */
        patch: operations["patch_profile_v1_auth__provider__profiles__name__patch"];
        trace?: never;
    };
    "/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Oauth Callback
         * @description Provider-agnostic OAuth callback.
         *
         *     This route intentionally does not require a JWT because OAuth providers
         *     redirect browser tabs here after the user leaves the app. The pending-auth
         *     state nonce is the callback credential; it maps back to the initiating
         *     account and profile.
         *
         *     Some public OAuth clients require a fixed localhost callback path. We
         *     dispatch to the correct provider by looking up the ``state`` value in the
         *     pending-auth table.
         */
        get: operations["oauth_callback_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Nested Callback */
        get: operations["oauth_nested_callback_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth2 Loopback Callback */
        get: operations["oauth2_loopback_callback_oauth2callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Provider Callback
         * @description Unauthenticated OAuth callback protected by the pending-auth state nonce.
         */
        get: operations["provider_callback_v1_auth__provider__callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/{provider}/exchange-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange Code
         * @description Manual paste-code path for OAuth flows where the provider shows the
         *     authorization code on screen instead of redirecting.
         */
        post: operations["exchange_code_v1_auth__provider__exchange_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/{provider}/profiles/{name}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile Status */
        get: operations["profile_status_v1_auth__provider__profiles__name__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/{provider}/profiles/{name}/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Profile Api Key
         * @description Create or update the CALLER's own API-key profile.
         *
         *     A thin wrapper over :func:`upsert_api_key_profile`; the tenant-facing contract is simply
         *     "whatever that does, to my own account".
         */
        put: operations["set_profile_api_key_v1_auth__provider__profiles__name__api_key_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/{provider}/profiles/{name}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Profile */
        post: operations["refresh_profile_v1_auth__provider__profiles__name__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_v1_oauth_connections_get"];
        put?: never;
        /** Start Connection Oauth */
        post: operations["start_connection_oauth_v1_oauth_connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connection */
        get: operations["get_connection_v1_oauth_connections__connection_id__get"];
        put?: never;
        post?: never;
        /** Delete Connection */
        delete: operations["delete_connection_v1_oauth_connections__connection_id__delete"];
        options?: never;
        head?: never;
        /** Patch Connection */
        patch: operations["patch_connection_v1_oauth_connections__connection_id__patch"];
        trace?: never;
    };
    "/v1/oauth/connections/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Api Key Connection
         * @description Create an api-key-authenticated connection (no OAuth round-trip).
         *
         *     The key is stored (encrypted at rest) in the same credential-blob slot the
         *     chat path reads for this connection, so it is usable on a real chat call
         *     immediately. The key is never echoed back or logged.
         */
        post: operations["create_api_key_connection_v1_oauth_connections_api_key_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth/connections/{connection_id}/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Connection Api Key
         * @description Replace the stored API key on an api-key connection.
         *
         *     Accepts an active OR errored connection: replacing the key is exactly how a
         *     user recovers a connection that errored on a bad/missing key, so a
         *     successful replace re-activates it (SF-291 review RF2-1).
         */
        put: operations["set_connection_api_key_v1_oauth_connections__connection_id__api_key_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth/connections/{connection_id}/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Connection Token
         * @description Return a fresh access token for the connection.
         *
         *     Consumed by SF backend plugins that delegate token management to
         *     aigateway. The strategy refreshes against the upstream provider if
         *     the cached credential is within the refresh window.
         */
        get: operations["get_connection_token_v1_oauth_connections__connection_id__token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/oauth/connections/{connection_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Connection */
        post: operations["refresh_connection_v1_oauth_connections__connection_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description OpenAI-compatible model listing, aggregated from all loaded provider plugins.
         *
         *     Each row carries the OME-479 locked hybrid summary (canonical dispatchable
         *     ``id`` + effective ``supported_parameters``/``supported_tools`` + literal
         *     ``reject`` + a same-origin detail URL), composed from each plugin's own
         *     provider-local rule set.
         */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/admit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admit Model */
        post: operations["admit_model_v1_models_admit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Providers
         * @description List enabled model providers whose credentials a caller can manage.
         */
        get: operations["list_providers_v1_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model-parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Parameters */
        get: operations["model_parameters_v1_model_parameters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Completions */
        post: operations["chat_completions_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountIdentity */
        AccountIdentity: {
            /** Sub */
            sub?: string | null;
            /** Email */
            email?: string | null;
            /** Name */
            name?: string | null;
            /** Raw */
            raw?: {
                [key: string]: unknown;
            };
        };
        /** AccountOut */
        AccountOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at?: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** AdminAccountList */
        AdminAccountList: {
            /** Accounts */
            accounts: components["schemas"]["AdminAccountOut"][];
            /** Total */
            total: number;
        };
        /**
         * AdminAccountOut
         * @description One tenant, as the console lists it.
         *
         *     `username` IS the Cloudflare-verified email address — `cloudflare_identity` keys the account on
         *     it, so there is no separate email field to drift out of step.
         */
        AdminAccountOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at?: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * AdminCacheInfoOut
         * @description Live state of the global response cache, for the console's cache section.
         *
         *     ``revisions`` are the constants every cache key embeds; a snapshot manifest that disagrees
         *     with them would load rows the gateway can never serve, which is why the console shows the
         *     live values beside the upload form.
         */
        AdminCacheInfoOut: {
            /** Serving */
            serving: boolean;
            /** Row Count */
            row_count: number;
            /** Revisions */
            revisions: {
                [key: string]: string;
            };
        };
        /** AdminCacheJobList */
        AdminCacheJobList: {
            /** Jobs */
            jobs: components["schemas"]["AdminCacheJobOut"][];
        };
        /**
         * AdminCacheJobOut
         * @description One snapshot load attempt, as the console lists and polls it.
         */
        AdminCacheJobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** State */
            state: string;
            /** Mode */
            mode: string;
            /** Actor */
            actor: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Staged Rows */
            staged_rows?: number | null;
            /** Live Before */
            live_before?: number | null;
            /** Live After */
            live_after?: number | null;
            /** Inserted Rows */
            inserted_rows?: number | null;
            /** Updated Rows */
            updated_rows?: number | null;
            /**
             * Manifest Present
             * @default false
             */
            manifest_present: boolean;
            /**
             * Forced
             * @default false
             */
            forced: boolean;
            /** Warnings */
            warnings?: string[];
            /** Refusal */
            refusal?: string | null;
            /** Error */
            error?: string | null;
        };
        /** AdminProfileList */
        AdminProfileList: {
            /** Profiles */
            profiles: components["schemas"]["AdminProfileOut"][];
        };
        /**
         * AdminProfileOut
         * @description One credential profile belonging to a tenant.
         *
         *     `account_label` is the MASKED display form (`"API key ····WXYZ"`). The raw key is never present
         *     in this model — there is no field for it, which is the point.
         */
        AdminProfileOut: {
            /** Id */
            id: string;
            /** Account Id */
            account_id: string;
            /** Provider */
            provider: string;
            /** Name */
            name: string;
            /** Account Label */
            account_label?: string | null;
            state: components["schemas"]["ProfileState"];
            /**
             * Auth Type
             * @enum {string}
             */
            auth_type: "oauth" | "api_key";
            defaults: components["schemas"]["ProfileDefaults"];
            /** Last Refreshed At */
            last_refreshed_at?: string | null;
        };
        /** ApiKeyValidationResponse */
        ApiKeyValidationResponse: {
            /** Provider */
            provider: string;
            state: components["schemas"]["ApiKeyValidationState"];
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
            stage?: components["schemas"]["ApiKeyValidationStage"] | null;
            /** Retry After Seconds */
            retry_after_seconds?: number | null;
            /** Probe Model */
            probe_model?: string | null;
        };
        /**
         * ApiKeyValidationStage
         * @enum {string}
         */
        ApiKeyValidationStage: "authentication" | "readiness";
        /**
         * ApiKeyValidationState
         * @enum {string}
         */
        ApiKeyValidationState: "valid" | "invalid" | "expired" | "no_quota" | "permission_denied" | "rate_limited" | "unavailable" | "misconfigured";
        /** Body_upload_snapshot_v1_admin_cache_snapshots_post */
        Body_upload_snapshot_v1_admin_cache_snapshots_post: {
            /**
             * Snapshot
             * @description gzip'd single-table pg_dump of the cache
             */
            snapshot: string;
            /**
             * Manifest
             * @description the .manifest.json snapshot-cache emitted beside the archive
             */
            manifest?: string | null;
            /**
             * Mode
             * @default merge
             */
            mode: string;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /**
             * Acknowledge Loss
             * @default false
             */
            acknowledge_loss: boolean;
        };
        /** CreateAccountRequest */
        CreateAccountRequest: {
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /** Display Name */
            display_name?: string | null;
        };
        /**
         * CreateAdminAccountRequest
         * @description Provision a tenant ahead of their first request.
         *
         *     No password field, deliberately. In `cloudflare_headers` mode an account is only ever reachable
         *     by presenting the verified header, and `account_for_identity` stores an empty hash that cannot
         *     match any candidate password. Accepting one here would imply a login path that does not exist.
         */
        CreateAdminAccountRequest: {
            /** Email */
            email: string;
            /** Display Name */
            display_name?: string | null;
        };
        /**
         * CreateApiKeyConnectionRequest
         * @description Create an api-key-authenticated connection (no OAuth round-trip).
         */
        CreateApiKeyConnectionRequest: {
            /** Provider */
            provider: string;
            /** Label */
            label?: string | null;
            /**
             * Api Key
             * Format: password
             */
            api_key: string;
        };
        /** CreateOAuthConnectionRequest */
        CreateOAuthConnectionRequest: {
            /** Provider */
            provider: string;
            /** Label */
            label?: string | null;
            /** Redirect Uri */
            redirect_uri?: string | null;
        };
        /** ExchangeCodeRequest */
        ExchangeCodeRequest: {
            /** Code */
            code: string;
            /** State */
            state: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Token */
            token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            account: components["schemas"]["AccountOut"];
        };
        /** OAuthConnectionListResponse */
        OAuthConnectionListResponse: {
            /** Connections */
            connections?: components["schemas"]["OAuthConnectionResponse"][];
        };
        /** OAuthConnectionResponse */
        OAuthConnectionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Provider */
            provider: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "active" | "expired" | "revoked" | "error";
            /**
             * Auth Type
             * @default oauth
             * @enum {string}
             */
            auth_type: "oauth" | "api_key";
            account?: components["schemas"]["AccountIdentity"] | null;
            /** Credential Locator */
            credential_locator: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at?: string | null;
            /** Last Refreshed At */
            last_refreshed_at?: string | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Is Duplicate
             * @default false
             */
            is_duplicate: boolean;
        };
        /**
         * OAuthConnectionTokenResponse
         * @description Short-lived access token + expiry for an active OAuth connection.
         *
         *     Returned by GET /v1/oauth/connections/{id}/token for SF backend plugins
         *     that consume aigateway-managed tokens instead of reading provider CLI
         *     credential stores directly.
         */
        OAuthConnectionTokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * PatchAdminAccountRequest
         * @description Both fields optional; omitted means unchanged.
         *
         *     `is_active=False` is the lockout mechanism — `account_for_identity` returns None for a
         *     deactivated account, so the next request 401s. There is no delete: it would cascade
         *     `oauth_connections` and orphan `credential_blobs`, which have no foreign key.
         */
        PatchAdminAccountRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** PatchAdminProfileRequest */
        PatchAdminProfileRequest: {
            defaults?: components["schemas"]["ProfileDefaults"] | null;
            /** Account Label */
            account_label?: string | null;
        };
        /** PatchOAuthConnectionRequest */
        PatchOAuthConnectionRequest: {
            /** Label */
            label?: string | null;
        };
        /** PatchProfileRequest */
        PatchProfileRequest: {
            defaults?: components["schemas"]["ProfileDefaults"] | null;
            /** Account Label */
            account_label?: string | null;
        };
        /**
         * ProfileDefaults
         * @description Per-profile fallback values applied when the chat body omits a field.
         */
        ProfileDefaults: {
            /** Model */
            model?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Timeout Seconds */
            timeout_seconds?: number | null;
            /** Reasoning Effort */
            reasoning_effort?: string | null;
        };
        /**
         * ProfileState
         * @enum {string}
         */
        ProfileState: "pending" | "authenticated" | "error";
        /**
         * SetAdminApiKeyRequest
         * @description Attach or replace a provider API key on a tenant's profile.
         *
         *     `hide_input_in_errors` matters here more than anywhere else in the app: without it a validation
         *     failure echoes the offending value back in the 422 body, which for this model is the API key.
         */
        SetAdminApiKeyRequest: {
            /**
             * Api Key
             * Format: password
             */
            api_key: string;
            defaults?: components["schemas"]["ProfileDefaults"] | null;
        };
        /** SetApiKeyRequest */
        SetApiKeyRequest: {
            /**
             * Api Key
             * Format: password
             */
            api_key: string;
            defaults?: components["schemas"]["ProfileDefaults"] | null;
        };
        /**
         * SetConnectionApiKeyRequest
         * @description Replace the stored API key on an existing api-key connection.
         */
        SetConnectionApiKeyRequest: {
            /**
             * Api Key
             * Format: password
             */
            api_key: string;
        };
        /** StartAuthRequest */
        StartAuthRequest: {
            /** Name */
            name: string;
            defaults?: components["schemas"]["ProfileDefaults"] | null;
            /** Redirect Uri */
            redirect_uri?: string | null;
        };
        /** StartOAuthConnectionResponse */
        StartOAuthConnectionResponse: {
            /**
             * Connection Id
             * Format: uuid
             */
            connection_id: string;
            /** Authorize Url */
            authorize_url: string;
            /** State */
            state: string;
            /**
             * Expires In
             * @default 600
             */
            expires_in: number;
        };
        /** ValidateApiKeyRequest */
        ValidateApiKeyRequest: {
            /** Provider */
            provider: string;
            /**
             * Api Key
             * Format: password
             */
            api_key: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** _AdmitRequest */
        _AdmitRequest: {
            /** Model Id */
            model_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
        };
    };
    create_account_v1_accounts_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Aigw-Provisioning-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_accounts_v1_admin_accounts_get: {
        parameters: {
            query?: {
                /** @description Substring match on address or display name */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAccountList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_account_v1_admin_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_v1_admin_accounts__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_account_v1_admin_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchAdminAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_account_profiles_v1_admin_accounts__account_id__profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProfileList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_profile_v1_admin_accounts__account_id__profiles__provider___name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                provider: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_account_profile_v1_admin_accounts__account_id__profiles__provider___name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                provider: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchAdminProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_account_api_key_v1_admin_accounts__account_id__profiles__provider___name__api_key_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                provider: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAdminApiKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cache_info_v1_admin_cache_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCacheInfoOut"];
                };
            };
        };
    };
    upload_snapshot_v1_admin_cache_snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_snapshot_v1_admin_cache_snapshots_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCacheJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cache_jobs_v1_admin_cache_snapshots_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCacheJobList"];
                };
            };
        };
    };
    get_cache_job_v1_admin_cache_snapshots_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCacheJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_api_key_v1_oauth_connections_api_key_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateApiKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_v1_auth_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_provider_profiles_v1_auth__provider__profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_oauth_v1_auth__provider__profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_v1_auth__provider__profiles__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_v1_auth__provider__profiles__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_profile_v1_auth__provider__profiles__name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_callback_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_nested_callback_auth_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth2_loopback_callback_oauth2callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_callback_v1_auth__provider__callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exchange_code_v1_auth__provider__exchange_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_status_v1_auth__provider__profiles__name__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_profile_api_key_v1_auth__provider__profiles__name__api_key_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetApiKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_profile_v1_auth__provider__profiles__name__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_v1_oauth_connections_get: {
        parameters: {
            query?: {
                provider?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthConnectionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_connection_oauth_v1_oauth_connections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOAuthConnectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartOAuthConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connection_v1_oauth_connections__connection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_connection_v1_oauth_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_connection_v1_oauth_connections__connection_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchOAuthConnectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_key_connection_v1_oauth_connections_api_key_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiKeyConnectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_connection_api_key_v1_oauth_connections__connection_id__api_key_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetConnectionApiKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connection_token_v1_oauth_connections__connection_id__token_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthConnectionTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_connection_v1_oauth_connections__connection_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    admit_model_v1_models_admit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_AdmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_v1_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    model_parameters_v1_model_parameters_get: {
        parameters: {
            query: {
                model: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_completions_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
