"""openrouter model seeds — mirrors ``aigateway/plugins/openrouter_provider/settings.py``.

Slugs are copied verbatim from that list, so the two can be compared by eye. The canonical
``openrouter/`` prefix is applied by :meth:`ProviderSeed.ids`, never written here.

AIDEV-NOTE: when aigateway's list changes, ``test_declared_models_match_aigateway.py`` fails
until this tuple matches. Add or remove the slug; never edit the guard.
"""

from screamingface_engine.world.models.registry import ProviderSeed

OPENROUTER = ProviderSeed(
    provider="openrouter",
    slugs=(
        "openrouter/anthropic/claude-fable-5",
        "openrouter/anthropic/claude-haiku-4.5",
        "openrouter/openai/gpt-5.5",
        "openrouter/openai/gpt-5.4",
        "openrouter/anthropic/claude-opus-4.8",
        "openrouter/google/gemini-3.1-pro-preview",
        "openrouter/google/gemini-3-flash-preview",
        "openrouter/moonshotai/kimi-k2.6",
        "openrouter/moonshotai/kimi-k3",
        "openrouter/deepseek/deepseek-v4-pro",
        "openrouter/qwen/qwen3.6-plus",
        "openrouter/anthropic/claude-opus-5",
        "openrouter/x-ai/grok-4.6",
        "openrouter/openai/gpt-5.6-sol",
        "openrouter/qwen/qwen3.8-max",
        "openrouter/openai/gpt-5.6-terra",
        "openrouter/x-ai/grok-4.5",
        "openrouter/anthropic/claude-sonnet-5",
        "openrouter/deepseek/deepseek-v4-pro-0813",
        "openrouter/qwen/qwen3.8-2.4t-a95b",
        "openrouter/nvidia/nemotron-3.5-lightning",
        "openrouter/upstage/solar-pro4",
        "openrouter/meta/muse-glimmer-30b",
        "openrouter/meta/muse-spark-1.2",
        "openrouter/sakana/sakana-namazu",
        "openrouter/qwen/qwen3.7-flash",
        "openrouter/deepseek/deepseek-v4-flash-0731",
        "openrouter/tencent/hy3",
        "openrouter/openai/gpt-5.6-luna",
        "openrouter/z-ai/glm-5.2",
        "openrouter/xiaomi/mimo-v2.5",
        "openrouter/google/gemini-3.6-flash",
        "openrouter/nvidia/nemotron-3-ultra-550b-a55b",
        "openrouter/minimax/minimax-m3",
        "openrouter/meituan/longcat-2.0",
        "openrouter/thinkingmachines/inkling",
        "openrouter/openai/gpt-5.6-sol-pro",
        "openrouter/openai/gpt-5.6-luna-pro",
        "openrouter/anthropic/claude-opus-5-fast",
        "openrouter/openrouter/auto-beta",
        "openrouter/openrouter/fusion",
        "openrouter/sakana/fugu-ultra",
        "openrouter/inclusionai/ling-3.0-flash",
        "openrouter/nex-agi/nex-n2-mini",
        "openrouter/liquid/lfm-2.5-2.6b:free",
        "openrouter/thinkingmachines/inkling-small",
        "openrouter/google/gemini-3.5-flash-lite",
        "openrouter/mistralai/ministral-14b-2512",
        "openrouter/google/gemini-3.5-flash",
        "openrouter/mistralai/mistral-large-2512",
        "openrouter/mistralai/mistral-medium-3-5",
        "openrouter/meta/muse-spark-1.1",
        "openrouter/aion-labs/aion-3.0",
        "openrouter/aion-labs/aion-3.0-mini",
        "openrouter/openai/gpt-5.6-sol:batch",
        "openrouter/openai/gpt-5.6-terra-pro",
        "openrouter/openai/gpt-5.2",
        "openrouter/openai/gpt-5.2-pro",
        "openrouter/openai/gpt-5",
        "openrouter/openai/gpt-5-mini",
        "openrouter/openai/gpt-4.1-mini",
        "openrouter/openai/gpt-oss-120b",
        "openrouter/anthropic/claude-opus-5:batch",
        "openrouter/anthropic/claude-sonnet-5:batch",
        "openrouter/anthropic/claude-fable-5:batch",
        "openrouter/anthropic/claude-opus-4.6",
        "openrouter/anthropic/claude-opus-4.5",
        "openrouter/anthropic/claude-sonnet-4.6",
        "openrouter/anthropic/claude-sonnet-4.5",
        "openrouter/qwen/qwen3-coder",
        "openrouter/deepseek/deepseek-v4-flash",
        "openrouter/mistralai/ministral-3b-2512",
        "openrouter/microsoft/phi-4",
    ),
)

__all__ = ["OPENROUTER"]
