"""Hop 1 of the cross-stack cache-hit contract: the gateway PRODUCES the hit fixture.

FEATURE: cache-entry metadata end to end
(spec ``docs/spec/2026-09-28-aigateway-cache-hit-metadata.md``
§3.2).
STORY: as an Engine maintainer I test my hit path against the bytes this gateway really sends,
so a change to the gateway's hit shape fails MY suite, not a production run.

The fixture ``tests/fixtures/cache_hit_contract/openrouter_hit.json`` is not written by hand. This
test drives the real chat route — a priced miss, then the identical request as a hit, through the
real Tortoise store — normalizes the values that change on every run, and compares the result to
the file. The Engine suite (``apps/screamingface-engine/tests/unit/test_cache_hit_contract.py``)
reads the same file by repository path; apps never import each other.

AIDEV-NOTE: a deliberate change to the hit shape is a CONTRACT change. Regenerate with
``SF_REGENERATE_CONTRACT_FIXTURES=1 uv run pytest tests/unit/test_cache_hit_contract_fixture.py``,
then regenerate the Engine's run-events fixture the same way, and let both consumer suites say
whether they still hold.
"""

from __future__ import annotations

import json
import os
import re
from importlib.resources import files
from pathlib import Path
from typing import Any
from unittest.mock import patch

from fastapi.testclient import TestClient
from jsonschema import Draft202012Validator

from tests.unit import test_chat_cache_entry_metadata as chat_cache
from tests.unit.test_chat_cache_entry_metadata import (
    _create_connection,
    _install_real,
    _post,
    _priced_dispatch,
)

# The arrangement of the chat-route slice, reused rather than copied: an admin-authenticated
# client with the request cache on, and a VALID key-readiness result (autouse there, so it is
# re-bound here to apply to this module too).
chat_client = chat_cache.chat_client
_api_key_validation_ok = chat_cache._api_key_validation_ok

FIXTURE = Path(__file__).resolve().parents[1] / "fixtures/cache_hit_contract/openrouter_hit.json"
REGENERATE = "SF_REGENERATE_CONTRACT_FIXTURES"

# The fixed stand-ins for per-run values. Each is VALID for its field, so the consumers parse the
# fixture exactly as they parse a live response.
_TRACE_ID = "4bf92f3577b34da6a3ce929d0e0e4736"
_CACHE_KEY = "0123456789ab"
_CALL_ID = "call_" + "0" * 32
_OBSERVED_AT = "2026-09-28T00:00:00Z"
_LATENCY_MS = 812

_HEX32 = re.compile(r"[0-9a-f]{32}")


def _normalized(response: Any) -> dict[str, Any]:
    """The hit with every per-run value replaced — after asserting each one is well-formed."""
    headers = {name: response.headers[name] for name in sorted(response.headers)}
    # Recomputed by any transport that re-serves the body; not part of the contract.
    headers.pop("content-length")
    assert re.fullmatch(r"[0-9a-f]{12}", headers["x-aigw-cache-key"])
    assert _HEX32.fullmatch(headers["x-aigw-trace-id"])
    headers["x-aigw-cache-key"] = _CACHE_KEY
    headers["x-aigw-trace-id"] = _TRACE_ID

    body = response.json()
    aigw = body["_aigw"]
    accounting = aigw["usage_accounting"]
    reference = accounting["cache"]["reference"]
    assert _HEX32.fullmatch(aigw["trace_id"])
    assert re.fullmatch(r"call_[0-9a-f]{32}", accounting["gateway_call_id"])
    assert re.fullmatch(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z", reference["observed_at"])
    assert type(reference["latency"]["provider_latency_ms"]) is int
    aigw["trace_id"] = _TRACE_ID
    accounting["gateway_call_id"] = _CALL_ID
    reference["observed_at"] = _OBSERVED_AT
    reference["latency"]["provider_latency_ms"] = _LATENCY_MS
    return {
        "description": (
            "A real aigateway cache-hit response (OpenRouter, priced miss then identical hit). "
            "Generated by apps/aigateway/tests/unit/test_cache_hit_contract_fixture.py; "
            f"regenerate with {REGENERATE}=1. Per-run values are normalized."
        ),
        "headers": headers,
        "body": body,
    }


def _schema() -> dict[str, Any]:
    resource = files("aigateway.plugins.taxonomy").joinpath("usage_accounting.schema.json")
    return json.loads(resource.read_text(encoding="utf-8"))


def test_the_checked_in_hit_fixture_is_what_the_gateway_sends(
    credential_blobs: Any, chat_client: TestClient
) -> None:
    _create_connection(chat_client)
    store = _install_real(chat_client)
    with patch("litellm.acompletion", _priced_dispatch()):
        assert _post(chat_client).headers["X-AIGW-Cache"] == "miss"
        hit = _post(chat_client)
    assert hit.status_code == 200, hit.text
    assert hit.headers["X-AIGW-Cache"] == "hit"
    (write,) = store.set_calls
    assert write.metadata is not None

    # The two fields this unit adds travel from the stored row to the hit verbatim (spec §3.1).
    reference = hit.json()["_aigw"]["usage_accounting"]["cache"]["reference"]
    assert reference["response_model"] == write.metadata.response_model
    assert reference["response_model"]  # the dispatch reports one, so it must not be lost
    assert reference["observed_at"] == write.metadata.observed_at
    assert reference["latency"]["provider_latency_ms"] == write.metadata.provider_latency_ms
    assert reference["direct_cost"] == write.metadata.direct_cost

    produced = _normalized(hit)
    Draft202012Validator(_schema()).validate(produced["body"]["_aigw"])

    if os.environ.get(REGENERATE) == "1":
        FIXTURE.parent.mkdir(parents=True, exist_ok=True)
        FIXTURE.write_text(json.dumps(produced, indent=2) + "\n", encoding="utf-8")
    assert FIXTURE.exists(), f"missing {FIXTURE}; generate it with {REGENERATE}=1"
    assert json.loads(FIXTURE.read_text(encoding="utf-8")) == produced, (
        f"the gateway's hit shape changed. If that is deliberate, regenerate with {REGENERATE}=1 "
        "and then regenerate the Engine's run-events fixture the same way."
    )


def test_the_fixture_carries_the_saved_cost_the_consumers_assert() -> None:
    """Pins the numbers the Engine and SDK consumers assert, so all three hops name one value."""
    body = json.loads(FIXTURE.read_text(encoding="utf-8"))["body"]
    accounting = body["_aigw"]["usage_accounting"]
    reference = accounting["cache"]["reference"]

    assert accounting["cache"]["status"] == "hit"
    assert reference["direct_cost"] == {
        "status": "reported",
        "amount": "0.012345",
        "unit": "openrouter_credits",
        "source": "openrouter.usage.cost",
    }
    assert reference["incurred_in_current_request"] is False
    assert accounting["attempts"] == []
    assert body["_aigw"]["request_economics"]["direct_cost_status"] == "not_applicable"
